import {
  fetchTranscript,
  YoutubeTranscriptDisabledError,
  YoutubeTranscriptNotAvailableError,
  YoutubeTranscriptNotAvailableLanguageError,
  YoutubeTranscriptTooManyRequestError,
  YoutubeTranscriptVideoUnavailableError,
  YoutubeTranscriptInvalidVideoIdError,
  type TranscriptConfig,
  type TranscriptResult,
  type TranscriptSegment as YtSegment,
} from "youtube-transcript-plus";
import {
  extractVideoId,
  formatTimestamp,
  thumbnailUrl,
  type TranscriptApiResponse,
  type TranscriptSegment,
} from "@/lib/transcript";

function browserUserAgent() {
  return (
    process.env.YT_USER_AGENT ||
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36"
  );
}

/**
 * Optional HTTP(S) proxy for YouTube requests.
 * Datacenter IPs (Vercel) are often blocked — set YT_PROXY_URL if needed,
 * e.g. http://user:pass@proxy-host:port
 */
function proxyFetchFactory() {
  const proxyUrl = process.env.YT_PROXY_URL?.trim();
  if (!proxyUrl) return undefined;

  // eslint-disable-next-line @typescript-eslint/no-require-imports
  const undici = require("undici") as typeof import("undici");
  const agent = new undici.ProxyAgent(proxyUrl);

  type FetchArgs = {
    url: string;
    method?: "GET" | "POST";
    body?: string;
    headers?: Record<string, string>;
    lang?: string;
    userAgent?: string;
    signal?: AbortSignal;
  };

  return async ({
    url,
    method,
    body,
    headers,
    lang,
    userAgent,
    signal,
  }: FetchArgs) => {
    const res = await undici.fetch(url, {
      method: method ?? "GET",
      body,
      signal,
      dispatcher: agent,
      headers: {
        ...(lang ? { "Accept-Language": lang } : {}),
        ...(userAgent ? { "User-Agent": userAgent } : {}),
        ...headers,
      },
    });
    return res as unknown as Response;
  };
}

function buildConfig(lang?: string): TranscriptConfig & { videoDetails: true } {
  const proxied = proxyFetchFactory();
  const base: TranscriptConfig & { videoDetails: true } = {
    lang,
    userAgent: browserUserAgent(),
    retries: 1,
    retryDelay: 600,
    videoDetails: true,
  };

  if (!proxied) return base;

  return {
    ...base,
    videoFetch: proxied,
    playerFetch: proxied,
    transcriptFetch: proxied,
  };
}

/** Convert `m:ss` / `h:mm:ss` → seconds */
function parseTimestampToSeconds(time: string): number {
  const parts = time.split(":").map((p) => Number(p));
  if (parts.some((n) => !Number.isFinite(n))) return 0;
  if (parts.length === 3) return parts[0] * 3600 + parts[1] * 60 + parts[2];
  if (parts.length === 2) return parts[0] * 60 + parts[1];
  if (parts.length === 1) return parts[0];
  return 0;
}

function shouldTryFallback(err: unknown): boolean {
  // On Vercel, YouTube often returns "not available" / rate-limit / bot blocks
  // even when captions exist — retry via public relay.
  if (
    err instanceof YoutubeTranscriptNotAvailableError ||
    err instanceof YoutubeTranscriptNotAvailableLanguageError ||
    err instanceof YoutubeTranscriptTooManyRequestError ||
    err instanceof YoutubeTranscriptDisabledError
  ) {
    return true;
  }
  const msg = err instanceof Error ? err.message : String(err);
  return /blocked|captcha|sign in|bot|429|503|timeout|fetch failed|ECONNRESET|ENOTFOUND/i.test(
    msg
  );
}

async function fetchOEmbed(videoId: string): Promise<{
  title: string | null;
  author: string | null;
}> {
  try {
    const res = await fetch(
      `https://www.youtube.com/oembed?url=${encodeURIComponent(
        `https://www.youtube.com/watch?v=${videoId}`
      )}&format=json`,
      {
        headers: { "User-Agent": browserUserAgent() },
        next: { revalidate: 3600 },
      }
    );
    if (!res.ok) return { title: null, author: null };
    const data = (await res.json()) as { title?: string; author_name?: string };
    return {
      title: data.title ?? null,
      author: data.author_name ?? null,
    };
  } catch {
    return { title: null, author: null };
  }
}

/** Promo / boilerplate lines injected by youtube-transcript.ai */
function isRelayJunkLine(line: string): boolean {
  const l = line.toLowerCase();
  return (
    l.includes("youtube-transcript.ai") ||
    l.includes("interactive version") ||
    l.includes("transcript generated by") ||
    l.includes("free youtube transcript") ||
    l.includes("ask the video") ||
    l.includes("ai summary") ||
    l.includes("chapter outline") ||
    l.includes("subtitle download") ||
    l.startsWith("## ") ||
    l.startsWith("source video:") ||
    l.startsWith("to request") ||
    /^https?:\/\/youtube-transcript\.ai\b/i.test(line)
  );
}

/**
 * Public relay used when YouTube blocks datacenter IPs (Vercel).
 * Same source as the original static HTML prototype.
 */
async function fetchViaTranscriptRelay(
  videoId: string
): Promise<TranscriptApiResponse> {
  const relayBase =
    process.env.YT_TRANSCRIPT_RELAY_URL?.replace(/\/$/, "") ||
    "https://youtube-transcript.ai/transcript";

  const res = await fetch(`${relayBase}/${videoId}.txt`, {
    headers: {
      "User-Agent": browserUserAgent(),
      Accept: "text/plain,*/*",
    },
    // Don't cache failures aggressively on the edge of our function
    cache: "no-store",
  });

  if (res.status === 404) {
    throw new YoutubeTranscriptNotAvailableError(videoId);
  }
  if (!res.ok) {
    throw new Error(`Transcript relay failed (status ${res.status}).`);
  }

  const raw = await res.text();
  if (!raw.trim()) {
    throw new YoutubeTranscriptNotAvailableError(videoId);
  }

  let title = "";
  let language: string | null = null;
  const segments: TranscriptSegment[] = [];

  for (const rawLine of raw.split("\n")) {
    const line = rawLine.trim();
    if (!line) continue;

    // Metadata headers (not transcript body)
    if (line.startsWith("# Transcript:")) {
      title = line.replace("# Transcript:", "").trim();
      continue;
    }
    if (line.startsWith("Language:")) {
      language = line.replace(/^Language:\s*/i, "").replace(/\s*[·|].*$/, "").trim() || null;
      continue;
    }

    // Drop relay promo / marketing / interactive links
    if (isRelayJunkLine(line)) continue;

    // Only keep real caption lines: [0:00] text
    const match = line.match(/^\[([0-9:]+)\]\s*(.+)$/);
    if (match) {
      const time = match[1];
      const text = match[2].replace(/\s+/g, " ").trim();
      if (!text || isRelayJunkLine(text)) continue;
      const offset = parseTimestampToSeconds(time);
      segments.push({ time, text, offset, duration: 0 });
    }
  }

  if (segments.length === 0) {
    throw new YoutubeTranscriptNotAvailableError(videoId);
  }

  const oembed = await fetchOEmbed(videoId);
  const rawText = segments
    .map((s) => (s.time ? `[${s.time}] ${s.text}` : s.text))
    .join("\n");

  return {
    videoId,
    title: title || oembed.title || `YouTube Video (${videoId})`,
    author: oembed.author,
    language,
    thumbnail: thumbnailUrl(videoId),
    segments,
    rawText,
  };
}

async function fetchViaYoutubeDirect(
  videoId: string,
  lang?: string
): Promise<TranscriptApiResponse> {
  const result: TranscriptResult = await fetchTranscript(
    videoId,
    buildConfig(lang)
  );
  const { videoDetails, segments: rawSegments } = result;

  const segments: TranscriptSegment[] = rawSegments.map((s: YtSegment) => ({
    time: formatTimestamp(s.offset),
    text: s.text.replace(/\s+/g, " ").trim(),
    offset: s.offset,
    duration: s.duration,
  }));

  if (segments.length === 0) {
    throw new YoutubeTranscriptNotAvailableError(videoId);
  }

  const language = rawSegments[0]?.lang ?? lang ?? null;
  const rawText = segments
    .map((s) => (s.time ? `[${s.time}] ${s.text}` : s.text))
    .join("\n");

  return {
    videoId,
    title: videoDetails?.title || `YouTube Video (${videoId})`,
    author: videoDetails?.author ?? null,
    language,
    thumbnail: videoDetails?.thumbnails?.[0]?.url || thumbnailUrl(videoId),
    segments,
    rawText,
  };
}

export function mapErrorMessage(err: unknown): { status: number; message: string } {
  if (err instanceof YoutubeTranscriptInvalidVideoIdError) {
    return { status: 400, message: "Invalid YouTube URL or video ID." };
  }
  if (err instanceof YoutubeTranscriptVideoUnavailableError) {
    return { status: 404, message: "This video is unavailable or private." };
  }
  if (err instanceof YoutubeTranscriptDisabledError) {
    return {
      status: 404,
      message: "Transcripts are disabled for this video by the creator.",
    };
  }
  if (
    err instanceof YoutubeTranscriptNotAvailableError ||
    err instanceof YoutubeTranscriptNotAvailableLanguageError
  ) {
    return {
      status: 404,
      message: "No captions/transcript found for this video.",
    };
  }
  if (err instanceof YoutubeTranscriptTooManyRequestError) {
    return {
      status: 429,
      message:
        "YouTube rate-limited this request. Try again shortly, or configure YT_PROXY_URL for Vercel.",
    };
  }

  const msg = err instanceof Error ? err.message : "Failed to fetch transcript.";
  if (/blocked|captcha|sign in|bot/i.test(msg)) {
    return {
      status: 503,
      message:
        "YouTube blocked the request from this server IP. Set YT_PROXY_URL (residential proxy) for Vercel deployments.",
    };
  }

  return { status: 500, message: msg };
}

/**
 * 1) Direct YouTube (works locally / with proxy)
 * 2) Public relay fallback (works on Vercel when YouTube blocks datacenter IPs)
 */
export async function getTranscriptForVideo(
  input: string,
  lang?: string
): Promise<TranscriptApiResponse> {
  const videoId = extractVideoId(input);
  if (!videoId) {
    throw new YoutubeTranscriptInvalidVideoIdError();
  }

  const preferRelay =
    process.env.YT_PREFER_RELAY === "1" ||
    process.env.YT_PREFER_RELAY === "true" ||
    // Vercel datacenter IPs are usually blocked by YouTube — use relay first unless disabled
    (process.env.VERCEL === "1" &&
      process.env.YT_PREFER_RELAY !== "0" &&
      !process.env.YT_PROXY_URL?.trim());

  if (preferRelay) {
    try {
      return await fetchViaTranscriptRelay(videoId);
    } catch {
      // fall through to direct
    }
    return fetchViaYoutubeDirect(videoId, lang);
  }

  try {
    return await fetchViaYoutubeDirect(videoId, lang);
  } catch (err) {
    // Don't fallback for clearly invalid / unavailable videos
    if (
      err instanceof YoutubeTranscriptInvalidVideoIdError ||
      err instanceof YoutubeTranscriptVideoUnavailableError
    ) {
      throw err;
    }

    if (!shouldTryFallback(err)) {
      throw err;
    }

    try {
      return await fetchViaTranscriptRelay(videoId);
    } catch (relayErr) {
      // Prefer a clear "not available" if both failed that way
      if (
        relayErr instanceof YoutubeTranscriptNotAvailableError ||
        err instanceof YoutubeTranscriptNotAvailableError
      ) {
        throw new YoutubeTranscriptNotAvailableError(videoId);
      }
      throw relayErr;
    }
  }
}
